version: '3.8'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: moniquedb
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - todo-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:3000"
    depends_on:
      - db
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge

volumes:
  db_data:
